replicaCount: 3
image:
  repository: maybetuandat/vdt_backend
  pullPolicy: IfNotPresent
  tag: "1.0"
  
service:
  type: NodePort
  port: 8080
  nodePort: 30002

database:
  host: vdt-db-postgres-chart
  port: 5432
  name: student_management
  user: postgres
  password: "123456"

resources: {}
