replicaCount: 3
image:
  repository: maybetuandat/vdt_backend
  pullPolicy: IfNotPresent
  tag: "2.10"
  
service:
  type: NodePort
  port: 8080
  nodePort: 30002

database:
  host: vdt-database-postgres-chart
  port: 5432
  name: student_management
  user: postgres
  password: "123456"

# Thêm resource limits cho backend (quan trọng vì có 3 replicas)
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"  # 3 pods x 256Mi = 768Mi total
    cpu: "300m"